# Generated by Django 6.0.7 on 2026-08-03 06:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('trade_type', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=10)),
                ('asset_class', models.CharField(choices=[('CRYPTO', 'Crypto'), ('STOCKS', 'Stocks'), ('FOREX', 'Forex'), ('OPTIONS', 'Options'), ('FUTURES', 'Futures')], default='CRYPTO', max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='CLOSED', max_length=15)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Trade setup logic, execution notes, and review', null=True)),
                ('emotion', models.CharField(choices=[('DISCIPLINED', 'Disciplined'), ('FOMO', 'FOMO'), ('REVENGE', 'Revenge'), ('FEARFUL', 'Fearful'), ('GREEDY', 'Greedy'), ('IMPULSIVE', 'Impulsive'), ('PATIENT', 'Patient')], default='DISCIPLINED', max_length=20)),
                ('rating', models.IntegerField(default=3, help_text='Execution rating from 1 to 5 stars')),
                ('chart_entry', models.ImageField(blank=True, null=True, upload_to='charts/entry/')),
                ('chart_exit', models.ImageField(blank=True, null=True, upload_to='charts/exit/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trades.strategy')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
