# Generated by Django 6.0.7 on 2026-08-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_strategy_user_trade_user_alter_strategy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma or hash separated tags e.g. #FVG, #LiquidityRaid', max_length=255, null=True),
        ),
    ]
