# Generated by Django 6.0.7 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='session',
            field=models.CharField(choices=[('ASIAN', 'Asian Session'), ('LONDON', 'London Session'), ('NEW_YORK', 'New York Session')], default='NEW_YORK', max_length=20),
        ),
    ]
