# Generated by Django 6.0.7 on 2026-09-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_trade_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)')], default='USD', max_length=5),
        ),
    ]
